repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy src/
        language: system
        pass_filenames: false
        types: [python]

      - id: notebooks
        name: test notebooks
        entry: uv run jupyter nbconvert --to notebook --execute --output /tmp/nb_test.ipynb notebooks/01_explore_dataset.ipynb
        language: system
        pass_filenames: false
        always_run: true
